In [43]:
import http.client

conn = http.client.HTTPConnection("r-function-orderbook:8203")
payload = ""
conn.request("GET", "/api/functions/values/obi_state/BTCUSDT", payload)

res = conn.getresponse()
json_data = res.read()

print(json_data.decode("utf-8"))

{"data":[{"lr_mu":-0.10725449103917684,"regime_share":0.0,"frag_fast":35.512911442637865,"z_score_x_9_mu":-0.9999998524615825,"z_score_x_2_x":0.07149916653715908,"imbalanceEma9":-0.9999999818292237,"imbalanceEma":-0.8020521043345723,"dbid_x":0.003468138899447486,"z_score9_mu":-0.7963964506918679,"lq_mu":0.012080886555214195,"z_score_x_9_x":3.3392459043871976e-9,"regime_cooldown_until":0,"dt_slow":61.88436101446174,"imbalanceEma2":-0.8020521043345723,"lq_x":0.01096713400635738,"depth_x":3.6597460226162144,"bd_x":1.4438670149373383,"bd_mu":-0.615634042544157,"z_score_var_2_x":0.07149916653715908,"regime_n":602486.0,"dask_mu":0.6213057118721635,"z_score_var_9_x":3.3392459043871976e-9,"timestamp":0,"dbid_mu":0.005671669328006634,"instant":1789143016971125830,"z_score2_x":0.07149916653715908,"dt_fast":50.47354122627176,"z_score_var_9_mu":-0.9999998524615825,"depth_mu":1.3553481059513255,"frag_slow":32.930452187139934,"z_score_var_2_mu":-0.5273797018429025,"dask_x":1.439869543184548,"z_score2_mu":-0.5273797018429025,"z_score9_x":0.000034118741442133094,"z_score_x_2_mu":-0.5273797018429025,"symbol":"BTCUSDT","lr_x":0.2451796418371994}]}

In [44]:
import json
import pandas as pd

data = json.loads(json_data)

df = pd.DataFrame(data["data"])

In [45]:
df

,lr_mu,regime_share,frag_fast,z_score_x_9_mu,z_score_x_2_x,imbalanceEma9,imbalanceEma,dbid_x,z_score9_mu,lq_mu,...,z_score_var_9_mu,depth_mu,frag_slow,z_score_var_2_mu,dask_x,z_score2_mu,z_score9_x,z_score_x_2_mu,symbol,lr_x
0,-0.107254,0.0,35.512911,-1.0,0.071499,-1.0,-0.802052,0.003468,-0.796396,0.012081,...,-1.0,1.355348,32.930452,-0.52738,1.43987,-0.52738,0.000034,-0.52738,BTCUSDT,0.24518

In [46]:
import requests

url = "http://r-function-orderbook:8203/api/functions/values/obi_state"

response = requests.get(url)

print(response.json())

{'data': [{'key': 'obi_state.__wd_cooldown_bybit_orderbook_x', 'values': [{'instant': 1789127645086330935}]}, {'key': 'obi_state.ADAUSDT', 'values': [{'regime_share': 0.0, 'regime_cooldown_until': 0, 'timestamp': 0, 'dbid_x': 86409165478.26505, 'z_score_x_2_x': 0.015552308085616123, 'dbid_mu': 258837.23081587564, 'depth_x': 920819112171.9456, 'frag_fast': 4.124845749896523e-06, 'lr_x': 0.6337268112818971, 'z_score9_mu': 0.27020802395604726, 'z_score_var_2_x': 0.015552308085616123, 'dt_fast': 85.52304910117974, 'imbalanceEma9': -0.0665141639641525, 'imbalanceEma': 0.26085462984715285, 'depth_mu': 910954.894046573, 'z_score_x_9_mu': 0.022900098129443935, 'lq_mu': 0.017315640746503012, 'regime_n': 379460.0, 'lr_mu': -0.5093717620946808, 'instant': 1789143028960551108, 'bd_mu': 69401.56579348192, 'dt_slow': 87.50132058084851, 'frag_slow': 5.567701665131172e-06, 'z_score2_mu': 0.2130220786485144, 'z_score_var_9_x': 0.007798526412956929, 'bd_x': 115316270257.3953, 'z_score_var_9_mu': 0.022900098129443935, 'imbalanceEma2': 0.26085462984715285, 'z_score2_x': 0.015552308085616123, 'symbol': 'ADAUSDT', 'dask_x': 50467509215.538605, 'z_score_var_2_mu': 0.2130220786485144, 'dask_mu': 189435.66502239375, 'z_score_x_2_mu': 0.2130220786485144, 'z_score_x_9_x': 0.007798526412956929, 'z_score9_x': 0.00010028888171117017, 'lq_x': 0.02109738653824708}]}, {'key': 'obi_state.DOTUSDT', 'values': [{'instant': 1789143029159887695, 'dask_mu': 1421.9586732989276, 'timestamp': 0, 'imbalanceEma9': -0.3675629640615946, 'z_score_x_9_mu': -0.35076952877498413, 'z_score_var_9_mu': -0.35076952877498413, 'imbalanceEma2': -0.2931133224701634, 'lq_x': 0.01579086782075208, 'z_score_x_2_x': 0.008885040854141891, 'imbalanceEma': -0.2931133224701634, 'frag_fast': 0.0007065846475184836, 'dbid_x': 2828560.985840235, 'dt_fast': 62.006381247946905, 'frag_slow': 0.0005488193610235693, 'depth_x': 1063616737.0829246, 'dask_x': 7725197.608672824, 'z_score_x_2_mu': -0.2232062452924069, 'symbol': 'DOTUSDT', 'z_score_var_9_x': 0.00040645581938718447, 'z_score2_mu': -0.2232062452924069, 'lr_mu': -0.07358827422565692, 'z_score9_x': 5.570345831728622e-06, 'z_score_var_2_x': 0.008885040854141891, 'regime_share': 1.7584436074482872e-134, 'regime_n': 440976.0, 'dbid_mu': 1035.5588709121248, 'z_score_x_9_x': 0.00040645581938718447, 'z_score2_x': 0.008885040854141891, 'bd_x': 11237452.068912752, 'lq_mu': 0.019468051197310585, 'regime_cooldown_until': 1789135582047010560, 'bd_mu': -386.3998023868031, 'z_score9_mu': -0.2909861898532654, 'dt_slow': 66.0838886007198, 'z_score_var_2_mu': -0.2232062452924069, 'depth_mu': 26699.667249978997, 'lr_x': 0.10043266144660663}]}, {'key': 'obi_state.AVAXUSDT', 'values': [{'regime_n': 468213.0, 'lq_mu': 0.01347526926103749, 'z_score_x_2_mu': 0.18843593249625643, 'z_score_x_2_x': 0.0641599889001053, 'z_score_var_9_mu': 0.2523001124630577, 'imbalanceEma': 0.38949720381254116, 'imbalanceEma2': 0.38949720381254116, 'dbid_x': 63490380.942561716, 'dt_slow': 75.08003850993893, 'lr_x': 0.19190311322441986, 'regime_cooldown_until': 1789135562440366336, 'dt_fast': 78.91354116487213, 'z_score_var_9_x': 0.0058541858112229105, 'instant': 1789143029159815178, 'z_score_var_2_mu': 0.18843593249625643, 'z_score9_x': 5.714597828422169e-05, 'z_score2_x': 0.0641599889001053, 'dask_x': 75962559.77797326, 'z_score_x_9_x': 0.0058541858112229105, 'imbalanceEma9': 0.17234785568795918, 'dbid_mu': 3261.270145956066, 'dask_mu': 3102.6855118505723, 'depth_mu': 18261.49516076182, 'depth_x': 1286813921.5355785, 'timestamp': 0, 'symbol': 'AVAXUSDT', 'z_score_x_9_mu': 0.2523001124630577, 'lr_mu': -0.13434747674496583, 'regime_share': 7.803394093572462e-41, 'z_score9_mu': 0.39570147090181496, 'bd_mu': 158.58463410549336, 'lq_x': 0.017415450432102787, 'frag_fast': 0.0026711749655631374, 'z_score2_mu': 0.18843593249625643, 'z_score_var_2_x': 0.0641599889001053, 'bd_x': 4174654.8853561673, 'frag_slow': 0.0015292574269121994}]}, {'key': 'obi_state.1000BONKUSDT', 'values': [{'lq_mu': 0.03196974970013209, 'lr_x': 0.14538369913501864, 'lr_mu': -0.10537375296005388, 'dask_mu': 6884785.628939297, 'z_score_x_9_x': 0.01104266820909506, 'dbid_mu': 6724500.545638006, 'dt_slow': 121.82906797192098, 'z_score9_mu': 0.28924243079302037, 'symbol': '1000BONKUSDT', 'z_score_var_9_x': 0.01104266820909506, 'frag_fast': 2.0520467355102813e-06, 'depth_x': 826446540646622.0, 'z_score2_mu': 0.21558826560389122, 'dask_x': 251328391450532.22, 'instant': 1789143029127547304, 'regime_n': 201672.0, 'imbalanceEma': 0.2776406337951276, 'regime_cooldown_until': 1789142119777407232, 'z_score2_x': 0.028813463435288345, 'dbid_x': 224450129861812.7, 'z_score9_x': 0.00014903739983273653, 'regime_share': 2.726699641464291e-22, 'depth_mu': 16922672.965056203, 'z_score_x_2_x': 0.028813463435288345, 'z_score_var_9_mu': -0.01805245207276862, 'z_score_var_2_x': 0.028813463435288345, 'bd_x': 106567379035914.78, 'z_score_x_2_mu': 0.21558826560389122, 'bd_mu': -160285.08330129212, 'dt_fast': 136.57955138752067, 'frag_slow': 2.832264651767601e-06, 'timestamp': 0, 'z_score_var_2_mu': 0.21558826560389122, 'z_score_x_9_mu': -0.01805245207276862, 'imbalanceEma2': 0.2776406337951276, 'lq_x': 0.03510395274149267, 'imbalanceEma9': -0.12842226113111846}]}, {'key': 'obi_state.PUMPFUNUSDT', 'values': [{'z_score_var_2_mu': 0.08269582575643891, 'imbalanceEma9': -0.049941958696584174, 'lq_x': 0.01661491317594024, 'dask_mu': 3444485.3689094144, 'depth_x': 141442269853739.9, 'dbid_mu': 2598153.7986151236, 'z_score_x_2_mu': 0.08269582575643891, 'z_score_x_9_x': 0.0022051605163210426, 'dask_x': 8377714779453.439, 'lq_mu': 0.0157875519440546, 'z_score9_x': 1.910257612198876e-05, 'bd_x': 21554683793614.438, 'frag_slow': 6.102126630507618e-07, 'regime_share': 5.094816097045976e-70, 'regime_cooldown_until': 1789133461548994816, 'z_score_var_9_mu': -0.004148382799704198, 'z_score_var_2_x': 0.019288729395815562, 'lr_x': 0.23711039640779655, 'imbalanceEma': 0.055759044686744724, 'dt_fast': 72.63718692440179, 'z_score2_x': 0.019288729395815562, 'symbol': 'PUMPFUNUSDT', 'dbid_x': 5858035727955.477, 'regime_n': 460254.0, 'timestamp': 0, 'z_score_var_9_x': 0.0022051605163210426, 'z_score_x_9_mu': -0.004148382799704198, 'dt_slow': 74.28534395085018, 'bd_mu': -846331.5702942907, 'imbalanceEma2': 0.055759044686744724, 'lr_mu': -0.16250029242155578, 'z_score2_mu': 0.08269582575643891, 'frag_fast': 4.5934057857702125e-07, 'depth_mu': 15863976.06116838, 'z_score_x_2_x': 0.019288729395815562, 'instant': 1789143028878835331, 'z_score9_mu': 0.05877907335483984}]}, {'key': 'obi_state.SOLUSDT', 'values': [{'z_score_var_2_mu': -0.13867629294276473, 'z_score2_mu': -0.13867629294276473, 'z_score_x_2_mu': -0.13867629294276473, 'lq_x': 0.010900091827210022, 'z_score_x_9_mu': -0.1630623612674576, 'z_score_var_2_x': 0.00679803689508136, 'z_score_x_2_x': 0.00679803689508136, 'depth_mu': 12197.124608726535, 'dt_fast': 56.91014583185073, 'imbalanceEma': -0.11523506749748319, 'imbalanceEma9': -0.18474491383593264, 'bd_x': 3647120.3603827013, 'symbol': 'SOLUSDT', 'dbid_x': 1766875.1323357532, 'frag_slow': 0.0007996701891303226, 'depth_x': 182924908.53540412, 'lr_mu': -0.18639628964865862, 'timestamp': 0, 'imbalanceEma2': -0.11523506749748319, 'regime_n': 589122.0, 'instant': 1789143029143431264, 'dbid_mu': 833.1096306691342, 'z_score9_x': 5.448670299316782e-06, 'lr_x': 0.262714853170674, 'regime_cooldown_until': 1789135509070688768, 'z_score_x_9_x': 0.00051764162075491, 'z_score_var_9_mu': -0.1630623612674576, 'lq_mu': 0.012697975702394221, 'regime_share': 0.0, 'frag_fast': 0.0011007672601576401, 'z_score_var_9_x': 0.00051764162075491, 'z_score2_x': 0.00679803689508136, 'bd_mu': 98.55265172438274, 'z_score9_mu': -0.1132490718878132, 'dask_mu': 734.5569789447514, 'dask_x': 865266.0661598169, 'dt_slow': 62.16685500638065}]}, {'key': 'obi_state.MONUSDT', 'values': [{'symbol': 'MONUSDT', 'imbalanceEma': -0.383298944427378, 'regime_n': 124207.0, 'z_score_var_2_x': 0.06084623292978818, 'z_score_var_9_x': 4.735000427388539e-05, 'depth_mu': 207511.33106264472, 'z_score2_mu': -0.018226378866868967, 'instant': 1789143029166579390, 'bd_mu': 26753.60710118749, 'regime_share': 0.0, 'frag_fast': 0.00020805927844414732, 'dt_slow': 187.78407943900683, 'imbalanceEma2': -0.383298944427378, 'dask_x': 1506196076.1502254, 'z_score_x_2_mu': -0.018226378866868967, 'imbalanceEma9': -0.9997122850026412, 'z_score_var_9_mu': -0.9987663127652034, 'z_score_x_9_mu': -0.9987663127652034, 'timestamp': 0, 'lr_x': 0.40989263401688714, 'lr_mu': -0.26924029738501903, 'z_score_var_2_mu': -0.018226378866868967, 'z_score9_x': 0.0003295517797596355, 'z_score2_x': 0.06084623292978818, 'z_score9_mu': -0.3656871346966562, 'z_score_x_9_x': 4.735000427388539e-05, 'bd_x': 24237155033.39983, 'lq_mu': 0.03510838191884458, 'depth_x': 96783659379.52856, 'dbid_x': 19045917180.02733, 'regime_cooldown_until': 0, 'dbid_mu': 61979.0671049088, 'dt_fast': 234.23031446674992, 'frag_slow': 0.00044557678461113, 'z_score_x_2_x': 0.06084623292978818, 'dask_mu': 35225.4600037213, 'lq_x': 0.05696324730245103}]}, {'key': 'obi_state.LINKUSDT', 'values': [{'lr_x': 0.16272297185842372, 'z_score2_x': 0.14322793734656597, 'z_score_x_9_x': 1.2969774155067524e-05, 'dt_fast': 82.08267886187058, 'regime_share': 1.5649430370426347e-33, 'imbalanceEma9': 0.9997569899588882, 'depth_mu': 4272.91556743831, 'lq_mu': 0.013523024439861996, 'frag_fast': 0.0062554574937842946, 'imbalanceEma2': 0.5550301135437254, 'z_score9_mu': 0.542323631360435, 'depth_x': 54846357.587218806, 'timestamp': 0, 'z_score_x_2_x': 0.14322793734656597, 'dt_slow': 79.13735534071631, 'z_score9_x': 0.00017144656975466623, 'lq_x': 0.017071330612931566, 'dask_mu': 250.54799498591578, 'dask_x': 156481.37276956713, 'bd_mu': 117.1311456336611, 'z_score2_mu': 0.08811706570437255, 'dbid_x': 169058.90104927807, 'frag_slow': 0.0072381719229617615, 'z_score_x_9_mu': 0.9990445956697868, 'symbol': 'LINKUSDT', 'regime_n': 453285.0, 'lr_mu': -0.08475876452218176, 'instant': 1789143028914941563, 'z_score_var_2_mu': 0.08811706570437255, 'z_score_var_2_x': 0.14322793734656597, 'z_score_x_2_mu': 0.08811706570437255, 'bd_x': 440308.43778904405, 'z_score_var_9_x': 1.2969774155067524e-05, 'regime_cooldown_until': 1789135576066923520, 'z_score_var_9_mu': 0.9990445956697868, 'dbid_mu': 367.6791406195769, 'imbalanceEma': 0.5550301135437254}]}, {'key': 'obi_state.ZECUSDT', 'values': [{'dt_fast': 60.50572569280279, 'lr_x': 0.12772451205975177, 'timestamp': 0, 'z_score9_x': 0.000141902662138752, 'frag_fast': 1.7129988891836332, 'regime_n': 619231.0, 'z_score_x_2_x': 0.03031335214496932, 'symbol': 'ZECUSDT', 'dask_x': 0.23235416176240964, 'frag_slow': 1.641310328723479, 'dt_slow': 63.50855880645643, 'instant': 1789143029169533558, 'z_score2_mu': 0.02522816668195082, 'lq_mu': 0.009751118167929815, 'lq_x': 0.010459921507998135, 'z_score_var_2_mu': 0.02522816668195082, 'depth_mu': 12.122929026362787, 'dbid_mu': 0.33652433835520734, 'z_score_x_2_mu': 0.02522816668195082, 'imbalanceEma9': -0.21849773677107964, 'z_score_x_9_mu': -0.10062063403546295, 'z_score2_x': 0.03031335214496932, 'dask_mu': 0.19108059228796195, 'z_score9_mu': 0.16390777249822852, 'regime_share': 0.0, 'imbalanceEma': 0.15328539724074774, 'depth_x': 190.96053213541398, 'z_score_var_2_x': 0.03031335214496932, 'bd_x': 0.4980637715411192, 'imbalanceEma2': 0.15328539724074774, 'z_score_var_9_x': 0.01257915685968494, 'z_score_var_9_mu': -0.10062063403546295, 'z_score_x_9_x': 0.01257915685968494, 'dbid_x': 0.2740702482241105, 'lr_mu': -0.06476697576245369, 'regime_cooldown_until': 1789134613084493312, 'bd_mu': 0.14544374606724542}]}, {'key': 'obi_state.DOGEUSDT', 'values': [{'z_score_var_9_mu': 0.8056225647303842, 'frag_slow': 6.915617768691371e-06, 'z_score_var_2_mu': 0.641721258485915, 'z_score_var_9_x': 0.007766337670864331, 'imbalanceEma9': 0.8920130759658629, 'z_score2_x': 0.015477174095596501, 'z_score9_mu': 0.6769796344914603, 'z_score2_mu': 0.641721258485915, 'z_score_x_9_mu': 0.8056225647303842, 'lq_mu': 0.01548492671964192, 'bd_mu': 749914.4895084682, 'timestamp': 0, 'z_score_x_2_mu': 0.641721258485915, 'symbol': 'DOGEUSDT', 'dask_mu': 66544.71165454392, 'z_score_x_9_x': 0.007766337670864331, 'imbalanceEma': 0.682952785643527, 'lr_x': 0.6202710775019806, 'imbalanceEma2': 0.682952785643527, 'regime_cooldown_until': 0, 'z_score9_x': 6.677180759142639e-05, 'regime_share': 2.295184216772499e-37, 'dt_fast': 64.08489342674042, 'instant': 1789143029198843528, 'lq_x': 0.015088534764503902, 'dt_slow': 68.56398244295062, 'frag_fast': 4.237632244769797e-06, 'z_score_x_2_x': 0.015477174095596501, 'dbid_mu': 816459.201163012, 'lr_mu': -0.39742901924074686, 'depth_mu': 2181647.2889995, 'dbid_x': 1132177897152.2913, 'dask_x': 20250432386.477634, 'regime_n': 494266.0, 'z_score_var_2_x': 0.015477174095596501, 'depth_x': 5692696211284.877, 'bd_x': 1231542100325.357}]}, {'key': 'obi_state.LITUSDT', 'values': [{'imbalanceEma9': -0.7179454852106215, 'imbalanceEma': -0.6964454950845176, 'z_score2_x': 0.07824789941298052, 'z_score_var_9_x': 0.0006264445046460685, 'regime_n': 317259.0, 'z_score_x_9_x': 0.0006264445046460685, 'z_score_var_9_mu': -0.7439848649608718, 'z_score_var_2_x': 0.07824789941298052, 'bd_mu': -930.9581546640786, 'dbid_x': 960249.5217542087, 'dask_mu': 1458.211294426438, 'z_score2_mu': -0.455308824392033, 'imbalanceEma2': -0.6964454950845176, 'bd_x': 5889351.0759934075, 'instant': 1789143029179534220, 'dask_x': 6638517.612316796, 'dt_fast': 98.96485019146412, 'dbid_mu': 527.2531397623591, 'regime_share': 4.670357206207805e-25, 'symbol': 'LITUSDT', 'z_score9_x': 7.176433056486704e-06, 'depth_mu': 3275.288141428034, 'z_score9_mu': -0.6958312096523431, 'timestamp': 0, 'lq_x': 0.02629837996934692, 'lr_mu': -0.07410655754816028, 'lq_mu': 0.02559811277658208, 'dt_slow': 92.16260747065029, 'frag_fast': 0.005699219624677019, 'frag_slow': 0.008527920352120575, 'z_score_var_2_mu': -0.455308824392033, 'regime_cooldown_until': 1789142269512795392, 'z_score_x_9_mu': -0.7439848649608718, 'depth_x': 17331431.782235935, 'z_score_x_2_mu': -0.455308824392033, 'z_score_x_2_x': 0.07824789941298052, 'lr_x': 0.12236824929344851}]}, {'key': 'obi_state.INJUSDT', 'values': [{'bd_x': 12863691.403164273, 'regime_n': 272532.0, 'symbol': 'INJUSDT', 'imbalanceEma2': -0.042100049113546534, 'dbid_x': 4066859.244146805, 'z_score_var_2_x': 0.03296625618320123, 'depth_x': 105816835.96534431, 'lq_mu': 0.023246601629221805, 'z_score9_mu': -0.05632272876853592, 'dt_slow': 107.91504053377285, 'timestamp': 0, 'z_score_var_2_mu': 0.023864918760704915, 'depth_mu': 5008.270095820324, 'z_score_x_2_x': 0.03296625618320123, 'dt_fast': 122.46857429763212, 'z_score9_x': 0.00018428256188577195, 'lq_x': 0.02668734187059881, 'dask_x': 11403753.738965657, 'instant': 1789143029172923268, 'lr_mu': -0.03200425627197469, 'frag_slow': 0.008484152665309826, 'regime_share': 1.2262976488099452e-104, 'z_score_x_9_mu': 0.38069389673871656, 'z_score2_x': 0.03296625618320123, 'bd_mu': -240.70031309831344, 'z_score_var_9_x': 0.00521195314950002, 'z_score_var_9_mu': 0.38069389673871656, 'imbalanceEma9': 0.455693738811082, 'z_score_x_2_mu': 0.023864918760704915, 'frag_fast': 0.007410746231766904, 'regime_cooldown_until': 1789138243239832320, 'imbalanceEma': -0.042100049113546534, 'z_score_x_9_x': 0.00521195314950002, 'z_score2_mu': 0.023864918760704915, 'dask_mu': 917.6507119088494, 'lr_x': 0.05388013457111122, 'dbid_mu': 676.9503988105361}]}, {'key': 'obi_state.FILUSDT', 'values': [{'regime_share': 0.0, 'imbalanceEma9': 0.9999074518277268, 'regime_cooldown_until': 1789135550168843776, 'dt_fast': 89.96326912395122, 'z_score_x_2_x': 0.07073603598354737, 'z_score_x_9_mu': 0.9995835049333546, 'dask_mu': 8220.827851700886, 'dt_slow': 93.98679855948536, 'z_score_x_9_x': 8.548374840752127e-06, 'frag_fast': 0.0029563071749764227, 'lq_mu': 0.02597688652770279, 'z_score_var_2_mu': 0.47307334378810506, 'bd_x': 55149617.53361652, 'z_score_var_9_x': 8.548374840752127e-06, 'symbol': 'FILUSDT', 'lq_x': 0.027418270396280815, 'imbalanceEma': 0.7531848296477945, 'frag_slow': 0.0032265995229928427, 'regime_n': 288619.0, 'dbid_mu': 9771.389205795911, 'z_score_var_9_mu': 0.9995835049333546, 'z_score_var_2_x': 0.07073603598354737, 'instant': 1789143029159837961, 'z_score2_mu': 0.47307334378810506, 'depth_mu': 37701.93400995243, 'imbalanceEma2': 0.7531848296477945, 'z_score9_x': 5.2835640052938626e-05, 'depth_x': 11910308064.01096, 'dask_x': 703000227.7461452, 'z_score_x_2_mu': 0.47307334378810506, 'lr_x': 0.13069814750714537, 'z_score9_mu': 0.746135611871225, 'bd_mu': 1550.5613540950246, 'lr_mu': -0.09232545851741582, 'timestamp': 0, 'z_score2_x': 0.07073603598354737, 'dbid_x': 672555834.7715667}]}, {'key': 'obi_state.__wd_cooldown_bybit_orderbook3', 'values': [{'instant': 1789143005085500525}]}, {'key': 'obi_state.WLDUSDT', 'values': [{'symbol': 'WLDUSDT', 'lq_x': 0.02447196231014742, 'depth_x': 309346911847.51935, 'dbid_mu': 41848.33918763607, 'dt_fast': 95.10239104752537, 'imbalanceEma9': 0.2196702870106762, 'z_score_var_9_mu': 0.1578759581277443, 'bd_x': 4882617780.026131, 'regime_n': 358616.0, 'z_score2_x': 0.010091029063403444, 'z_score_x_2_mu': -0.033172299355198456, 'z_score_x_9_x': 0.003697253002485769, 'regime_share': 3.327057720944695e-30, 'imbalanceEma': 0.013162055455509289, 'regime_cooldown_until': 1789135569499610880, 'imbalanceEma2': 0.013162055455509289, 'instant': 1789143029147126120, 'z_score_x_9_mu': 0.1578759581277443, 'bd_mu': 20970.918040129007, 'z_score_var_9_x': 0.003697253002485769, 'z_score9_x': 4.280332940229398e-05, 'lr_mu': -0.13269071820142994, 'z_score_x_2_x': 0.010091029063403444, 'lq_mu': 0.02535737410987451, 'timestamp': 0, 'frag_slow': 0.0002896994720259871, 'z_score_var_2_x': 0.010091029063403444, 'depth_mu': 598325.8678752532, 'dt_slow': 85.13725087993105, 'dask_mu': 20877.421147507062, 'z_score2_mu': -0.033172299355198456, 'z_score9_mu': 0.0072618202682188104, 'z_score_var_2_mu': -0.033172299355198456, 'dask_x': 1000888916.3504916, 'lr_x': 0.24520089930806718, 'frag_fast': 0.00046026086709765083, 'dbid_x': 3158026728.756912}]}, {'key': 'obi_state.SUIUSDT', 'values': [{'imbalanceEma2': -0.359903519782167, 'z_score_x_2_mu': -0.3459756656577536, 'dbid_mu': 4976.583013636423, 'lq_mu': 0.015905662093786407, 'imbalanceEma9': -0.9141278724699917, 'z_score_var_2_x': 0.0381705219429245, 'z_score_var_9_x': 0.0052123452204081815, 'imbalanceEma': -0.359903519782167, 'z_score2_x': 0.0381705219429245, 'lq_x': 0.017746707678431013, 'regime_cooldown_until': 1789133510584769792, 'frag_slow': 0.00019227388425870523, 'dask_mu': 10191.447508039308, 'bd_x': 211909932.2438523, 'lr_x': 0.18020730049972622, 'z_score9_mu': -0.3440685382768006, 'z_score2_mu': -0.3459756656577536, 'depth_x': 14567619778.583685, 'instant': 1789143029205416338, 'z_score_var_2_mu': -0.3459756656577536, 'bd_mu': -5214.864494402887, 'frag_fast': 0.00022918174446258076, 'timestamp': 0, 'dt_slow': 77.40289918481997, 'lr_mu': -0.11678295288435736, 'symbol': 'SUIUSDT', 'z_score_x_9_x': 0.0052123452204081815, 'z_score_x_2_x': 0.0381705219429245, 'dt_fast': 82.2188205023534, 'z_score_var_9_mu': -0.8417004103795818, 'regime_n': 442549.0, 'depth_mu': 74048.01955902185, 'z_score9_x': 0.00022916168170791069, 'z_score_x_9_mu': -0.8417004103795818, 'dask_x': 126624301.38199982, 'regime_share': 3.196032574263199e-35, 'dbid_x': 42677592.659768}]}, {'key': 'obi_state.XMRUSDT', 'values': [{'regime_cooldown_until': 1789141820820800256, 'z_score_var_9_x': 0.02796180792586356, 'dt_fast': 109.97603340260537, 'z_score9_mu': -0.17982482258035962, 'dbid_x': 0.3037527450621504, 'timestamp': 0, 'z_score_x_9_mu': 0.6264883784223934, 'z_score_var_9_mu': 0.6264883784223934, 'imbalanceEma9': 0.8018013273175622, 'frag_slow': 2.2266223099378273, 'dask_x': 4.802751090214178, 'dt_slow': 91.73994746799606, 'imbalanceEma': -0.15255742952763957, 'z_score_x_2_x': 0.024355338285724934, 'z_score_var_2_mu': -0.20877590155454595, 'instant': 1789143029133552933, 'z_score2_x': 0

In [47]:
data = response.json()
df = pd.DataFrame(data["data"])

In [48]:
df

,key,values
0,obi_state.__wd_cooldown_bybit_orderbook_x,[{'instant': 1789127645086330935}]
1,obi_state.ADAUSDT,"[{'regime_share': 0.0, 'regime_cooldown_until'..."
2,obi_state.DOTUSDT,"[{'instant': 1789143029159887695, 'dask_mu': 1..."
3,obi_state.AVAXUSDT,"[{'regime_n': 468213.0, 'lq_mu': 0.01347526926..."
4,obi_state.1000BONKUSDT,"[{'lq_mu': 0.03196974970013209, 'lr_x': 0.1453..."
5,obi_state.PUMPFUNUSDT,"[{'z_score_var_2_mu': 0.08269582575643891, 'im..."
6,obi_state.SOLUSDT,"[{'z_score_var_2_mu': -0.13867629294276473, 'z..."
7,obi_state.MONUSDT,"[{'symbol': 'MONUSDT', 'imbalanceEma': -0.3832..."
8,obi_state.LINKUSDT,"[{'lr_x': 0.16272297185842372, 'z_score2_x': 0..."
9,obi_state.ZECUSDT,"[{'dt_fast': 60.50572569280279, 'lr_x': 0.1277..."
10,obi_state.DOGEUSDT,"[{'z_score_var_9_mu': 0.8056225647303842, 'fra..."
11,obi_state.LITUSDT,"[{'imbalanceEma9': -0.7179454852106215, 'imbal..."
12,obi_state.INJUSDT,"[{'bd_x': 12863691.403164273, 'regime_n': 2725..."
13,obi_state.FILUSDT,"[{'regime_share': 0.0, 'imbalanceEma9': 0.9999..."
14,obi_state.__wd_cooldown_bybit_orderbook3,[{'instant': 1789143005085500525}]
15,obi_state.WLDUSDT,"[{'symbol': 'WLDUSDT', 'lq_x': 0.0244719623101..."
16,obi_state.SUIUSDT,"[{'imbalanceEma2': -0.359903519782167, 'z_scor..."
17,obi_state.XMRUSDT,[{'regime_cooldown_until': 1789141820820800256...
18,obi_state.TRXUSDT,"[{'z_score_x_9_x': 0.0030214503464744756, 'lq_..."
19,obi_state.MYXUSDT,"[{'z_score_var_9_x': 0.00034140975409546336, '..."
20,obi_state.NVDAUSDT,"[{'imbalanceEma9': 0.9811096684671013, 'z_scor..."
21,obi_state.XAGUSDT,"[{'frag_slow': 0.03298603048258537, 'z_score_v..."
22,obi_state.BNBUSDT,"[{'imbalanceEma2': 0.6148554155074707, 'z_scor..."
23,obi_state.TAOUSDT,"[{'imbalanceEma9': -0.9999841093129808, 'depth..."
24,obi_state.HBARUSDT,"[{'z_score_x_2_x': 0.013609338667266836, 'frag..."
25,obi_state.WIFUSDT,"[{'dt_slow': 97.42349661475292, 'frag_slow': 9..."
26,obi_state.DASHUSDT,"[{'z_score2_x': 0.06317988288121654, 'z_score9..."
27,obi_state.WLFIUSDT,"[{'regime_share': 2.241694381813184e-37, 'imba..."
28,obi_state.APTUSDT,"[{'z_score_var_9_mu': -0.8631037983869297, 'z_..."
29,obi_state.LTCUSDT,"[{'imbalanceEma': -0.29328006508851145, 'dt_fa..."
30,obi_state.LDOUSDT,"[{'frag_slow': 0.010405381488304092, 'regime_s..."
31,obi_state.__wd_cooldown_bybit_orderbook0,[{'instant': 1789137275086279262}]
32,obi_state.BTCUSDT,"[{'regime_share': 0.0, 'z_score2_mu': -0.65750..."
33,obi_state.__wd_cooldown_bybit_orderbook_nvda,[{'instant': 1789127645086330935}]
34,obi_state.CLUSDT,"[{'bd_x': 165059.01922170786, 'symbol': 'CLUSD..."
35,obi_state.ARBUSDT,"[{'timestamp': 0, 'dbid_mu': 4381.548268087823..."
36,obi_state.1000RATSUSDT,"[{'regime_n': 80570.0, 'imbalanceEma': 0.73645..."
37,obi_state.HYPEUSDT,"[{'lr_mu': -0.3875733983051888, 'depth_x': 108..."
38,obi_state.XRPUSDT,"[{'dask_mu': 71636.21271519217, 'lq_mu': 0.010..."
39,obi_state.CYBERUSDT,"[{'z_score_var_2_x': 0.014094372626797802, 'lq..."
40,obi_state.XAUUSDT,"[{'dt_fast': 97.24143747392013, 'z_score_var_2..."
41,obi_state.JTOUSDT,"[{'frag_slow': 0.004228699450895336, 'lr_x': 0..."
42,obi_state.__wd_cooldown_bybit_orderbook1000,[{'instant': 1789138655085384574}]
43,obi_state.XLMUSDT,"[{'bd_mu': -275578.89081310196, 'regime_cooldo..."
44,obi_state.ETHUSDT,"[{'timestamp': 0, 'symbol': 'ETHUSDT', 'z_scor..."
45,obi_state.1000PEPEUSDT,"[{'z_score_var_9_mu': 0.8793522003634966, 'z_s..."
46,obi_state.COMPUSDT,"[{'z_score_var_9_mu': 0.962562057957326, 'imba..."
47,obi_state.UNIUSDT,"[{'z_score_x_2_x': 0.01743794543354815, 'z_sco..."
48,obi_state.ASTERUSDT,"[{'lq_x': 0.03471849885662543, 'regime_share':..."
49,obi_state.OPUSDT,"[{'lq_mu': 0.025340756916027652, 'regime_n': 3..."
50,obi_state.__wd_cooldown_bybit_orderbook1,[{'instant': 1789137275086279262}]
51,obi_state.STGUSDT,"[{'lr_mu': -0.32904413815699457, 'z_score9_x':..."
52,obi_state.__wd_cooldown_bybit_orderbook2,[{'instant': 1789141535088863024}]
53,obi_state.ENAUSDT,"[{'z_score_var_2_x': 0.04158355111720541, 'z_s..."
54,obi_state.SHIB1000USDT,"[{'z_score2_mu': -0.20108844284890057, 'z_scor..."
55,obi_state.BCHUSDT,"[{'imbalanceEma9': 0.9800872193684573, 'z_scor..."

In [49]:
def values(setting="obi_state",
           code="BTCUSDT"):
    base_url = f"http://r-function-orderbook:8203/api/functions/values/{setting}/{code}"
    response = requests.get(base_url)

    if response.status_code == 200:
        return response.json()
    else:
        print(f"Error: {response.status_code}")
        return None

In [50]:
data=values("obi_state", "BTCUSDT")
df = pd.DataFrame(data["data"])

In [51]:
df

,depth_x,bd_mu,z_score_var_9_x,frag_fast,z_score_x_2_x,regime_cooldown_until,z_score_x_2_mu,imbalanceEma,z_score9_x,regime_n,...,dask_x,frag_slow,lr_mu,lr_x,imbalanceEma2,z_score_var_9_mu,dbid_x,dask_mu,bd_x,timestamp
0,7.419382,-2.242797,0.000333,27.217366,0.003398,0,-0.789641,-0.825423,0.000023,603063.0,...,4.32088,32.025612,-0.106517,0.243918,-0.825423,-0.981884,0.067415,2.258032,4.321787,0

In [57]:
def setting(setting="functions"):
    base_url = f"http://r-function-orderbook:8203/api/functions/setting/{setting}"
    response = requests.get(base_url)

    if response.status_code == 200:
        return response.json()
    else:
        print(f"Error: {response.status_code}")
        return None

In [58]:
# functions
f=setting("functions")
df = pd.DataFrame(f["data"])
df

               key                                             values
0  bybit_orderbook  [{'id': 0, 'code': 'code', 'settingCode': None...

In [59]:
# catalogs
f=setting("catalogs")
df = pd.DataFrame(f["data"])
df

             key                                             values
0  orderbook_sse  [{'id': None, 'code': 'orderbook_sse', 'routin...

In [60]:
# consumers
f=setting("consumers")
df = pd.DataFrame(f["data"])
df

             key                                             values
0  orderbook_sse  [{'id': None, 'code': None, 'key': 'setting_co...

In [61]:
# streams
f=setting("streams")
df = pd.DataFrame(f["data"])
df

,key,values
0,bybit_orderbook,"[{'id': None, 'isActive': True, 'key': 'bybit_..."
1,volume_spike_channel,"[{'id': None, 'isActive': True, 'key': 'volume..."
2,order_book_imbalance_channel,"[{'id': None, 'isActive': True, 'key': 'order_..."
3,message_shift,"[{'id': None, 'isActive': True, 'key': 'messag..."
4,regime_shift_channel,"[{'id': None, 'isActive': True, 'key': 'regime..."