In [1]:
import http.client

conn = http.client.HTTPConnection("r-function-orderbook:8203")
payload = ""
conn.request("GET", "/api/functions/values/obi_state/BTCUSDT", payload)

res = conn.getresponse()
json_data = res.read()

print(json_data.decode("utf-8"))

{"data":[{"imbalanceEma":-0.32611876902971676,"z_score_x_2_x":0.03634726076498955,"z_score_var_2_mu":-0.06031671660039878,"symbol":"BTCUSDT","imbalanceEma2":-0.32611876902971676,"z_score_var_2_x":0.03634726076498955,"lr_x":0.05687506000555637,"instant":1789052658345716959,"z_score2_mu":-0.06031671660039878,"z_score9_x":0.00036337501935036266,"z_score_var_9_x":0.0010431103822905847,"dbid_mu":0.11413640979671331,"z_score_var_9_mu":-0.9710819620019945,"dask_mu":0.20160757005650887,"z_score_x_2_mu":-0.06031671660039878,"z_score2_x":0.03634726076498955,"z_score_x_9_x":0.0010431103822905847,"dt_slow":64.52933033886895,"regime_n":429137.0,"bd_x":0.33401836400699153,"regime_share":8.756854652602388e-15,"z_score9_mu":-0.30716448006403274,"dask_x":0.12841771225444037,"imbalanceEma9":-0.9895188828286561,"lq_x":0.005701932498089105,"bd_mu":-0.0874711602597956,"z_score_x_9_mu":-0.9710819620019945,"frag_slow":55.82739856303763,"depth_x":1.3970881192709077,"regime_cooldown_until":0,"timestamp":0,"depth_mu":0.9950204689531886,"lr_mu":-0.020816174104570175,"lq_mu":0.0022219511251252073,"frag_fast":65.76518639376151,"dt_fast":68.5514541866941,"dbid_x":0.1865151418028428}]}

In [2]:
import json
import pandas as pd

data = json.loads(json_data)

df = pd.DataFrame(data["data"])

In [3]:
df

,imbalanceEma,z_score_x_2_x,z_score_var_2_mu,symbol,imbalanceEma2,z_score_var_2_x,lr_x,instant,z_score2_mu,z_score9_x,...,frag_slow,depth_x,regime_cooldown_until,timestamp,depth_mu,lr_mu,lq_mu,frag_fast,dt_fast,dbid_x
0,-0.326119,0.036347,-0.060317,BTCUSDT,-0.326119,0.036347,0.056875,1789052658345716959,-0.060317,0.000363,...,55.827399,1.397088,0,0,0.99502,-0.020816,0.002222,65.765186,68.551454,0.186515

In [7]:
import requests

url = "http://r-function-orderbook:8203/api/functions/values/obi_state"

response = requests.get(url)

print(response.json())

{'data': [{'key': 'obi_state.TAOUSDT', 'values': [{'dt_slow': 55.059822481468046, 'dbid_mu': 3.581686553510141, 'imbalanceEma': 0.39608470096126724, 'z_score_var_9_mu': 0.44003576564599245, 'frag_slow': 0.1037758966053264, 'dbid_x': 7.069362062908551, 'z_score_x_2_mu': 0.4065822019137831, 'dask_mu': 0.1490598774513477, 'lq_mu': 0.005187428090507629, 'lq_x': 0.005463386286878562, 'z_score_var_2_mu': 0.4065822019137831, 'frag_fast': 0.06711617211558984, 'imbalanceEma2': 0.39608470096126724, 'z_score_var_9_x': 0.0023751335495782178, 'lr_mu': -0.13799857008674937, 'imbalanceEma9': 0.39543440023505705, 'bd_mu': 3.4326266760587933, 'z_score2_mu': 0.4065822019137831, 'z_score_x_2_x': 0.010952537871980847, 'z_score_x_9_mu': 0.44003576564599245, 'z_score2_x': 0.010952537871980847, 'regime_n': 431049.0, 'dask_x': 2.18740361053552, 'regime_cooldown_until': 1789051937276612352, 'z_score9_mu': 0.3961032809820161, 'dt_fast': 51.95719904434711, 'z_score_x_9_x': 0.0023751335495782178, 'symbol': 'TAOUSDT', 'depth_mu': 57.32418278663039, 'depth_x': 2033.7565152144055, 'bd_x': 10.18264419040263, 'regime_share': 7.26170634774945e-20, 'timestamp': 0, 'instant': 1789052694826628734, 'z_score9_x': 1.9425600582766524e-05, 'z_score_var_2_x': 0.010952537871980847, 'lr_x': 0.1878082301612485}]}, {'key': 'obi_state.ZECUSDT', 'values': [{'symbol': 'ZECUSDT', 'dbid_x': 0.6260824533501155, 'depth_x': 2.8115839788828905, 'lq_x': 0.005656316245341581, 'regime_share': 4.1362770517060537e-69, 'z_score_x_2_x': 0.03587712685263687, 'z_score_x_2_mu': -0.14984488957983144, 'z_score_var_2_x': 0.03587712685263687, 'z_score_x_9_mu': 0.9440466429782404, 'dask_x': 0.20685755119874213, 'dask_mu': 0.20134368233168332, 'depth_mu': 1.9383718828737788, 'timestamp': 0, 'frag_fast': 2.5335926189841484, 'z_score2_x': 0.03587712685263687, 'frag_slow': 2.425005089778527, 'imbalanceEma': 0.057414087577810774, 'instant': 1789052694731339697, 'bd_x': 1.0462706908402102, 'z_score_x_9_x': 0.004070925645003745, 'imbalanceEma9': 0.980008538641925, 'z_score9_mu': 0.031054246118836115, 'bd_mu': 0.4045070908353608, 'z_score_var_9_mu': 0.9440466429782404, 'dbid_mu': 0.605850773167044, 'dt_fast': 60.02297257071772, 'dt_slow': 60.84804987634347, 'imbalanceEma2': 0.057414087577810774, 'z_score9_x': 0.0006980625216436005, 'lr_x': 0.06839913312320971, 'z_score_var_2_mu': -0.14984488957983144, 'z_score_var_9_x': 0.004070925645003745, 'regime_n': 413169.0, 'z_score2_mu': -0.14984488957983144, 'lq_mu': 0.00303772894005168, 'regime_cooldown_until': 0, 'lr_mu': -0.032334145254374294}]}, {'key': 'obi_state.ASTERUSDT', 'values': [{'frag_fast': 0.0006543495770881217, 'z_score2_x': 0.048167796442777244, 'z_score_var_9_mu': 0.9760744815243741, 'dask_mu': 1849.28112347862, 'z_score_var_2_mu': 0.4527858403183583, 'lr_x': 0.05884839596355254, 'z_score_x_9_mu': 0.9760744815243741, 'instant': 1789052694094824895, 'depth_x': 149649927.3637924, 'imbalanceEma2': 0.6651761989367311, 'dbid_x': 6355956.745967924, 'dbid_mu': 2266.0765710385804, 'lq_mu': -0.005689980735463804, 'dt_slow': 158.0013813986385, 'lr_mu': -0.02159378732419609, 'symbol': 'ASTERUSDT', 'z_score_var_2_x': 0.048167796442777244, 'depth_mu': 7468.258159957651, 'regime_cooldown_until': 0, 'z_score_var_9_x': 0.0007271693777609641, 'bd_mu': 416.7954475599605, 'imbalanceEma': 0.6651761989367311, 'bd_x': 109061376.41643114, 'timestamp': 0, 'z_score_x_9_x': 0.0007271693777609641, 'imbalanceEma9': 0.9911391164068339, 'z_score9_x': 8.717122563919755e-05, 'z_score_x_2_x': 0.048167796442777244, 'dask_x': 96642082.71415637, 'z_score_x_2_mu': 0.4527858403183583, 'frag_slow': 0.0009014415494378362, 'z_score2_mu': 0.4527858403183583, 'dt_fast': 126.49572469338635, 'lq_x': 0.020460305314870378, 'z_score9_mu': 0.6558629727232995, 'regime_n': 135021.0, 'regime_share': 2.655225691887616e-18}]}, {'key': 'obi_state.__wd_cooldown_bybit_orderbook3', 'values': [{'instant': 1789052683778679435}]}, {'key': 'obi_state.XMRUSDT', 'values': [{'imbalanceEma2': -0.7233208013645362, 'instant': 1789052694803252234, 'z_score_x_9_mu': -0.999650032258065, 'z_score9_mu': -0.7154178005576076, 'dask_mu': 1.1483784738661889, 'frag_fast': 1.8482228295843846, 'frag_slow': 2.8424857399150527, 'bd_mu': -0.8967874389394693, 'regime_share': 2.8230839312777847e-71, 'dt_slow': 86.50995520694254, 'dt_fast': 85.6384531368426, 'z_score_var_2_x': 0.022546482432242266, 'z_score_x_9_x': 8.405035332816463e-06, 'regime_n': 205597.0, 'depth_x': 5.472315748618602, 'z_score9_x': 6.645740111073925e-05, 'z_score2_mu': -0.532085643358009, 'dbid_x': 1.1046933250299058, 'z_score_x_2_mu': -0.532085643358009, 'z_score_x_2_x': 0.022546482432242266, 'lq_x': 0.013269564882075167, 'depth_mu': 3.4912992533941214, 'lr_mu': -0.03492616838681367, 'regime_cooldown_until': 0, 'lr_x': 0.07846976946017782, 'z_score_var_9_x': 8.405035332816463e-06, 'z_score_var_9_mu': -0.999650032258065, 'dask_x': 1.45682808410802, 'imbalanceEma': -0.7233208013645362, 'bd_x': 3.0706868070205915, 'dbid_mu': 0.25159103492671964, 'timestamp': 0, 'symbol': 'XMRUSDT', 'imbalanceEma9': -0.9999258296070378, 'lq_mu': 0.009897813961077376, 'z_score2_x': 0.022546482432242266, 'z_score_var_2_mu': -0.532085643358009}]}, {'key': 'obi_state.1000PEPEUSDT', 'values': [{'depth_mu': 22576536.826275907, 'z_score9_mu': 0.7334727575811771, 'dbid_x': 36776207513156.62, 'z_score_x_9_mu': 0.9660176155399325, 'z_score_var_9_x': 0.0014669948328657825, 'dbid_mu': 8503179.79154562, 'lr_mu': -0.13298160911134765, 'instant': 1789052694822697591, 'bd_x': 80838894425020.33, 'symbol': '1000PEPEUSDT', 'z_score2_mu': 0.7060957131829069, 'z_score2_x': 0.008042107940838249, 'depth_x': 378697298302033.44, 'imbalanceEma9': 0.9874140989292698, 'lq_x': 0.009851585804755402, 'bd_mu': 6506338.784957958, 'regime_cooldown_until': 0, 'dask_x': 19859621089256.047, 'frag_fast': 2.6255957256642335e-07, 'z_score_x_2_mu': 0.7060957131829069, 'z_score_x_9_x': 0.0014669948328657825, 'z_score_var_2_mu': 0.7060957131829069, 'imbalanceEma': 0.7405266837297353, 'regime_n': 233679.0, 'regime_share': 0.0034158528991730043, 'dt_fast': 73.25527551817699, 'lr_x': 0.2031333717204182, 'z_score_var_9_mu': 0.9660176155399325, 'z_score9_x': 5.304558420614795e-05, 'lq_mu': 0.005738576359017522, 'dt_slow': 82.36034120166067, 'dask_mu': 1996841.0065876627, 'imbalanceEma2': 0.7405266837297353, 'z_score_x_2_x': 0.008042107940838249, 'frag_slow': 5.946884563284973e-07, 'z_score_var_2_x': 0.008042107940838249, 'timestamp': 0}]}, {'key': 'obi_state.AVAXUSDT', 'values': [{'z_score_var_9_x': 4.217825758954021e-09, 'depth_mu': 4791.296318975259, 'regime_n': 245604.0, 'symbol': 'AVAXUSDT', 'regime_cooldown_until': 1789047308982000384, 'dask_x': 11447317.078986546, 'frag_fast': 0.002839973395751533, 'dask_mu': 956.5178142238877, 'dt_slow': 87.32123179065803, 'lr_x': 0.17702414181037046, 'dbid_mu': 1717.431565911133, 'z_score2_mu': 0.5431919600555849, 'imbalanceEma9': 0.9999999801927185, 'z_score_x_9_x': 4.217825758954021e-09, 'z_score_var_9_mu': 0.999999837920618, 'bd_x': 19453126.7703193, 'z_score_x_9_mu': 0.999999837920618, 'imbalanceEma': 0.8078774384760941, 'z_score9_x': 3.214014551211419e-05, 'z_score_x_2_mu': 0.5431919600555849, 'frag_slow': 0.0033752834955213585, 'dbid_x': 13502050.64790244, 'z_score_x_2_x': 0.06097131068603568, 'imbalanceEma2': 0.8078774384760941, 'depth_x': 96813359.81461087, 'instant': 1789052694825965702, 'z_score_var_2_x': 0.06097131068603568, 'bd_mu': 760.9137516872454, 'z_score9_mu': 0.8023882229984762, 'dt_fast': 86.89083517218866, 'regime_share': 7.9466429390732225e-115, 'lr_mu': -0.11055313843808703, 'lq_x': 0.009201461732039187, 'timestamp': 0, 'z_score_var_2_mu': 0.5431919600555849, 'z_score2_x': 0.06097131068603568, 'lq_mu': 0.002757193168522469}]}, {'key': 'obi_state.LDOUSDT', 'values': [{'lq_mu': -0.0014793078055080058, 'imbalanceEma2': 0.5023838013712771, 'z_score2_mu': 0.4962490967406225, 'z_score9_x': 0.00017730915164171528, 'dask_mu': 1766.9864953770427, 'dask_x': 28430887.39973043, 'lr_mu': -0.1784964797860899, 'z_score_var_2_x': 0.04421361886776814, 'dbid_x': 355913439.1897285, 'dt_slow': 141.492718778894, 'lr_x': 0.28904677040351867, 'depth_mu': 26496.556071723826, 'z_score_x_2_x': 0.04421361886776814, 'z_score9_mu': 0.4933279162894716, 'z_score_var_2_mu': 0.4962490967406225, 'z_score_var_9_mu': 0.6736232043898689, 'depth_x': 10340596299.559574, 'z_score_x_9_mu': 0.6736232043898689, 'regime_cooldown_until': 0, 'regime_n': 134015.0, 'regime_share': 0.0, 'z_score2_x': 0.04421361886776814, 'z_score_var_9_x': 0.02170270621496761, 'dt_fast': 138.7444025710377, 'frag_fast': 0.0005739657288397826, 'z_score_x_2_mu': 0.4962490967406225, 'z_score_x_9_x': 0.02170270621496761, 'bd_mu': 7577.839417849038, 'imbalanceEma9': 0.8193397792344715, 'instant': 1789052694819441603, 'frag_slow': 0.0010244066747924962, 'dbid_mu': 9344.82591322608, 'lq_x': 0.01661626470572079, 'timestamp': 0, 'symbol': 'LDOUSDT', 'imbalanceEma': 0.5023838013712771, 'bd_x': 374683018.43630886}]}, {'key': 'obi_state.HYPEUSDT', 'values': [{'z_score9_mu': -0.3521422090795259, 'frag_slow': 0.00888014580489807, 'z_score_x_9_mu': 0.6474737372835613, 'z_score_var_9_x': 0.02449008464644054, 'regime_cooldown_until': 0, 'timestamp': 0, 'dask_mu': 600.6395618437248, 'dbid_x': 268496.8821174727, 'frag_fast': 0.031208230201705395, 'z_score_x_2_x': 0.026118201945846124, 'dt_fast': 63.26900859974504, 'depth_x': 2804637.6193291885, 'regime_share': 0.0, 'bd_mu': -225.65973204873777, 'imbalanceEma2': -0.319857336605784, 'bd_x': 473327.27213464706, 'lq_x': 0.0061629283125889875, 'imbalanceEma': -0.319857336605784, 'z_score2_mu': -0.5862048055757456, 'z_score_x_2_mu': -0.5862048055757456, 'lq_mu': 0.003338774375475336, 'dt_slow': 63.56584096928604, 'symbol': 'HYPEUSDT', 'dask_x': 100057.0494323018, 'z_score_x_9_x': 0.02449008464644054, 'lr_mu': -0.5372110765374477, 'z_score_var_2_x': 0.026118201945846124, 'dbid_mu': 374.9798297949867, 'regime_n': 380732.0, 'z_score_var_2_mu': -0.5862048055757456, 'lr_x': 0.7353102958355185, 'z_score_var_9_mu': 0.6474737372835613, 'z_score9_x': 0.0009451049017206126, 'instant': 1789052694786966623, 'z_score2_x': 0.026118201945846124, 'imbalanceEma9': 0.8101131999751825, 'depth_mu': 2550.524604689176}]}, {'key': 'obi_state.SOLUSDT', 'values': [{'lq_x': 0.005136049861428383, 'z_score2_mu': -0.07581086237678411, 'z_score_var_2_x': 0.04100463976574555, 'regime_cooldown_until': 0, 'lr_x': 0.22329939239438007, 'frag_slow': 0.0014118951105085782, 'z_score_x_9_x': 0.002776445476244414, 'dbid_x': 951295.8056392699, 'imbalanceEma': 0.1399580743752552, 'bd_mu': -442.05688549139325, 'instant': 1789052694770543713, 'lq_mu': 0.0031607838526478173, 'z_score_var_9_x': 0.002776445476244414, 'dask_x': 388478.2359601315, 'regime_n': 394160.0, 'bd_x': 1922910.6552946623, 'symbol': 'SOLUSDT', 'frag_fast': 0.0010292005837647137, 'depth_mu': 4416.447537019754, 'z_score_x_9_mu': 0.21808110635894218, 'z_score2_x': 0.04100463976574555, 'imbalanceEma2': 0.1399580743752552, 'z_score9_mu': 0.13928341130711064, 'dbid_mu': 555.8184617936867, 'z_score_var_9_mu': 0.21808110635894218, 'dask_mu': 997.87534728508, 'dt_fast': 62.395036477606446, 'lr_mu': -0.17414211097893745, 'dt_slow': 64.23610109698517, 'imbalanceEma9': 0.1635712817603154, 'regime_share': 0.0, 'z_score_x_2_mu': -0.07581086237678411, 'z_score_x_2_x': 0.04100463976574555, 'depth_x': 30664824.55879514, 'z_score9_x': 2.88744013699722e-05, 'timestamp': 0, 'z_score_var_2_mu': -0.07581086237678411}]}, {'key': 'obi_state.1000BONKUSDT', 'values': [{'imbalanceEma': 0.1226132532573494, 'lr_x': 0.07757265170977738, 'z_score_var_9_mu': -0.6750800000000003, 'z_score_var_2_x': 0.08096026102269646, 'z_score_var_2_mu': 0.5320550385388613, 'depth_mu': 6921955.610165813, 'lq_mu': 0.004987759189864596, 'regime_n': 127022.0, 'z_score_x_9_x': 0.02163397895999993, 'z_score_x_9_mu': -0.6750800000000003, 'timestamp': 0, 'z_score2_x': 0.08096026102269646, 'bd_mu': 2937784.5243795905, 'dt_slow': 130.14835236929687, 'regime_cooldown_until': 1789052808314207232, 'dbid_mu': 4413037.858873474, 'dbid_x': 92081285051336.61, 'imbalanceEma2': 0.1226132532573494, 'imbalanceEma9': -0.8198000000000001, 'z_score_var_9_x': 0.02163397895999993, 'z_score2_mu': 0.5320550385388613, 'dask_mu': 1475253.3344938832, 'lq_x': 0.020316066125247226, 'dask_x': 4573871914050.096, 'symbol': '1000BONKUSDT', 'bd_x': 108226059435657.7, 'z_score_x_2_mu': 0.5320550385388613, 'dt_fast': 107.70684407462697, 'lr_mu': -0.025236807977375292, 'depth_x': 126877954881262.12, 'regime_share': 0.03282272355621996, 'frag_fast': 5.351516363520182e-06, 'z_score9_x': 0.0006767571847865201, 'frag_slow': 3.151864682392281e-06, 'instant': 1789052694721533851, 'z_score_x_2_x': 0.08096026102269646, 'z_score9_mu': 0.14953934620755938}]}, {'key': 'obi_state.WLFIUSDT', 'values': [{'dask_mu': 13731.869052091188, 'frag_slow': 0.0001710241203144868, 'depth_x': 26154330694.068035, 'bd_x': 2676684181.6432858, 'dt_slow': 151.9693866039076, 'regime_n': 89425.0, 'regime_cooldown_until': 0, 'imbalanceEma': 0.11462232355366489, 'z_score_x_2_x': 0.06670377901857946, 'z_score_x_9_x': 0.002549051578980501, 'symbol': 'WLFIUSDT', 'z_score2_x': 0.06670377901857946, 'dask_x': 355912691.0329978, 'lr_mu': -0.14568804616928327, 'depth_mu': 151471.9891491748, 'instant': 1789052694652923239, 'z_score_var_9_x': 0.002549051578980501, 'timestamp': 0, 'z_score_x_2_mu': -0.204070107425669, 'z_score_var_2_mu': -0.204070107425669, 'lq_x': 0.025463326809930388, 'dbid_mu': 36273.985009012344, 'frag_fast': 4.820206116625006e-05, 'z_score_var_2_x': 0.06670377901857946, 'lr_x': 0.2648269531872683, 'z_score_var_9_mu': 0.9550237953490934, 'lq_mu': 0.0009696881405392216, 'z_score9_mu': 0.08979192158497401, 'dt_fast': 116.90260599327189, 'imbalanceEma2': 0.11462232355366489, 'imbalanceEma9': 0.9836863924578461, 'regime_share': 0.0, 'dbid_x': 1637535608.5133748, 'z_score9_x': 0.0006209311481468888, 'bd_mu': 22542.115956921156, 'z_score_x_9_mu': 0.9550237953490934, 'z_score2_mu': -0.204070107425669}]}, {'key': 'obi_state.WIFUSDT', 'values': [{'z_score9_x': 0.00018597344625535106, 'z_score_x_2_mu': 0.18295138174654446, 'z_score_var_2_x': 0.04033815006896953, 'z_score_x_9_mu': 0.3580790815907611, 'regime_share': 1.477311114462806e-11, 'dbid_mu': 59943.33353203911, 'depth_x': 15541161447.685343, 'dt_slow': 101.05598478694918, 'lq_x': 0.011493095250653064, 'imbalanceEma': 0.056412043688535835, 'regime_n': 177699.0, 'z_score2_x': 0.04033815006896953, 'z_score_x_2_x': 0.04033815006896953, 'bd_mu': 24529.481538336848, 'z_score_var_2_mu': 0.18295138174654446, 'frag_fast': 0.0002405843143753769, 'bd_x': 8232131900.890537, 'z_score_var_9_x': 0.015984090764916668, 'depth_mu': 152144.78824787357, 'dt_fast': 96.5661949357312, 'symbol': 'WIFUSDT', 'imbalanceEma2': 0.056412043688535835, 'z_score2_mu': 0.18295138174654446, 'dask_mu': 35413.85199370227, 'lr_x': 0.24433918844848637, 'frag_slow': 0.0002794963803934242, 'dbid_x': 4352681906.365618, 'timestamp': 0, 'instant': 1789052694398434688, 'lr_mu': -0.14753811663032262, 'imbalanceEma9': 0.4883875386779007, 'lq_mu': 0.0035103926798162634, 'regime_cooldown_until': 1789051957147713280, 'z_score_var_9_mu': 0.3580790815907611, 'dask_x': 1945921877.6396792, 'z_score9_mu': 0.044069886688839696, 'z_score_x_9_x': 0.015984090764916668}]}, {'key': 'obi_state.XLMUSDT', 'values': [{'bd_x': 145656475753.59442, 'lq_mu': -0.0007093238170377991, 'z_score2_mu': -0.382679484660286, 'z_score9_mu': -0.6491610601973952, 'dbid_mu': 158280.52568365223, 'z_score_x_9_x': 2.616928032304595e-06, 'frag_slow': 7.699637972394464e-05, 'lr_x': 0.3213978566187094, 'dt_fast': 118.06962229497171, 'dask_mu': 180485.63933139676, 'regime_n': 153171.0, 'regime_share': 0.0, 'z_score_x_2_mu': -0.382679484660286, 'lr_mu': -0.21266100846049443, 'symbol': 'XLMUSDT', 'frag_fast': 5.909102687307013e-05, 'regime_cooldown_until': 0, 'imbalanceEma9': -0.999984750764082, 'z_score_var_9_x': 2.616928032304595e-06, 'z_score2_x': 0.043806093350699286, 'timestamp': 0, 'z_score_var_9_mu': -0.9999160291364388, 'dbid_x': 75273364880.50818, 'imbalanceEma2': -0.6589061627131365, 'bd_mu': -22205.113647744492, 'z_score_var_2_x': 0.043806093350699286, 'depth_mu': 482742.67616243096, 'lq_x': 0.014616136070263899, 'z_score_x_2_x': 0.043806093350699286, 'z_score_var_2_mu': -0.382679484660286, 'dt_slow': 127.92146689280047, 'depth_x': 128867916218.16331, 'imbalanceEma': -0.6589061627131365, 'z_score9_x': 0.000101239269844827, 'z_score_x_9_mu': -0.9999160291364388, 'instant': 1789052694669369333, 'dask_x': 32658591176.643185}]}, {'key': 'obi_state.SHIB1000USDT', 'values': [{'lr_x': 0.6551454665928556, 'z_score_var_2_x': 0.09312567326806587, 'dt_slow': 77.32411669075796, 'z_score_x_9_x': 4.384018178932254e-07, 'regime_cooldown_until': 1789047640252773376, 'regime_share': 9.345914769217002e-115, 'depth_x': 44805268478379.734, 'bd_mu': 1149911.9676562378, 'symbol': 'SHIB1000USDT', 'z_score_x_2_mu': 0.24901864324839734, 'frag_slow': 1.433033174230907e-05, 'z_score_x_2_x': 0.09312567326806587, 'imbalanceEma2': 0.6125162716081314, 'z_score_var_9_mu': 0.9999872103267348, 'dbid_x': 44131988861611.16, 'z_score_x_9_mu': 0.9999872103267348, 'dask_x': 1137064513189.3271, 'instant': 1789052694561567559, 'dt_fast': 73.11020775066926, 'depth_mu': 2391285.516760484, 'bd_x': 46214093736452.32, 'lr_mu': -0.5111384193862072, 'z_score_var_2_mu': 0.24901864324839734, 'z_score_var_9_x': 4.384018178932254e-07, 'z_score2_x': 0.09312567326806587, 'dbid_mu': 1501876.4820725028, 'timestamp': 0, 'regime_n': 340769.0, 'dask_mu': 351964.5144162643, 'lq_mu': 6.509915252754773e-05, 'z_score9_mu': 0.6014453650501765, 'z_score9_x': 0.0001307231622907674, 'frag_fast': 9.985897547907242e-06, 'imbalanceEma9': 0.9999980011365501, 'lq_x': 0.011685557096580475, 'imbalanceEma': 0.6125162716081314, 'z_score2_mu': 0.24901864324839734}]}, {'key': 'obi_state.COMPUSDT', 'values': [{'z_score9_mu': -0.10858086126642683, 'frag_slow': 0.06894392990360884, 'imbalanceEma9': -0.8111799112076394, 'bd_mu': -1.337687080815689, 'z_score_var_2_mu': -0.00992992138266632, 'depth_mu': 1049.2076392484323, 'regime_n': 47804.0, 'z_score_x_2_mu': -0.00992992138266632, 'z_score_var_9_mu': -0.6520147183869109, 'bd_x': 34847.04960511458, 'lq_x': 0.03472890547043696, 'regime_cooldown_until': 0, 'z_score_var_2_x': 0.02572567659518356, 'z_score_x_2_x': 0.02572567659518356, 'dask_mu': 33.913911086813265, 'imbalanceEma2': -0.1280975015425716, 'lq_mu': -0.028393209639002125, 'lr_x': 0.10263113768053363, 'regime_share': 0.0, 'lr_mu': -0.01760490721691972, 'timestamp': 0, 'instant': 1789052689590038565, 'dbid_mu': 32.57622400599758, 'z_score2_x': 0.02572567659518356, 'z_score_x_9_mu': -0.6520147183869109, 'z_score9_x': 0.0003900472263331887, 'z_score2_mu': -0.00992992138266632, 'symbol': 'COMPUSDT', 'imbalanceEma': -0.1280975015425716, 'z_score_var_9_x': 0.023896194116445862, 'dt_fast': 442.64361200058386, 'frag_fast': 0.04986448210635946, 'dt_slow': 416.6908491426932, 'dask_x': 32136.248250466357, 'depth_x': 9666624.13012666, 'z_score_x_9_x': 0.023896194116445862, 'dbid_x': 1555.1863940162634}]}, {'key': 'obi_state.__wd_cooldown_bybit_orderbook2', 'values': [{'instant': 1789052143777969231}]}, {'key': 'obi_state.DOGEUSDT', 'values': [{'symbol': 'DOGEUSDT', 'regime_cooldown_until': 0, 'frag_slow': 8.598719221234413e-06, 'lq_mu': 0.0025282885417207083, 'frag_fast': 9.116294844786351e-06, 'imbalanceEma': -0.566845616645717, 'dbid_x': 2223669712860.45, 'z_score2_x': 0.03225237539197159, 'dask_mu': 722879.4837244876, 'z_score_x_2_x': 0.03225237539197159, 'imbalanceEma2': -0.566845616645717, 'instant': 1789052694519123886, 'imbalanceEma9': -0.8582257567764531, 'lr_mu': -0.19290523183558037, 'lr_x': 0.27996822223459406, 'z_score9_x': 0.00011948078530657434, 'lq_x': 0.006264948420147957, 'bd_x': 2853146278754.38, 'regime_n': 309124.0, 'regime_share': 0.0, 'timestamp': 0, 'z_score_x_9_x': 0.01338584098306659, 'bd_mu': 1605.3852008740287, 'dask_x': 645764086029.1985, 'z_score_var_2_x': 0.032252

In [8]:
data = response.json()
df = pd.DataFrame(data["data"])

In [9]:
df

,key,values
0,obi_state.TAOUSDT,"[{'dt_slow': 55.059822481468046, 'dbid_mu': 3...."
1,obi_state.ZECUSDT,"[{'symbol': 'ZECUSDT', 'dbid_x': 0.62608245335..."
2,obi_state.ASTERUSDT,"[{'frag_fast': 0.0006543495770881217, 'z_score..."
3,obi_state.__wd_cooldown_bybit_orderbook3,[{'instant': 1789052683778679435}]
4,obi_state.XMRUSDT,"[{'imbalanceEma2': -0.7233208013645362, 'insta..."
5,obi_state.1000PEPEUSDT,"[{'depth_mu': 22576536.826275907, 'z_score9_mu..."
6,obi_state.AVAXUSDT,"[{'z_score_var_9_x': 4.217825758954021e-09, 'd..."
7,obi_state.LDOUSDT,"[{'lq_mu': -0.0014793078055080058, 'imbalanceE..."
8,obi_state.HYPEUSDT,"[{'z_score9_mu': -0.3521422090795259, 'frag_sl..."
9,obi_state.SOLUSDT,"[{'lq_x': 0.005136049861428383, 'z_score2_mu':..."
10,obi_state.1000BONKUSDT,"[{'imbalanceEma': 0.1226132532573494, 'lr_x': ..."
11,obi_state.WLFIUSDT,"[{'dask_mu': 13731.869052091188, 'frag_slow': ..."
12,obi_state.WIFUSDT,"[{'z_score9_x': 0.00018597344625535106, 'z_sco..."
13,obi_state.XLMUSDT,"[{'bd_x': 145656475753.59442, 'lq_mu': -0.0007..."
14,obi_state.SHIB1000USDT,"[{'lr_x': 0.6551454665928556, 'z_score_var_2_x..."
15,obi_state.COMPUSDT,"[{'z_score9_mu': -0.10858086126642683, 'frag_s..."
16,obi_state.__wd_cooldown_bybit_orderbook2,[{'instant': 1789052143777969231}]
17,obi_state.DOGEUSDT,"[{'symbol': 'DOGEUSDT', 'regime_cooldown_until..."
18,obi_state.__wd_cooldown_bybit_orderbook_nvda,[{'instant': 1789042363777874073}]
19,obi_state.UNIUSDT,"[{'bd_x': 1470624.6121011355, 'imbalanceEma': ..."
20,obi_state.WLDUSDT,"[{'regime_n': 205935.0, 'z_score_var_9_mu': 0...."
21,obi_state.LITUSDT,"[{'dask_mu': 409.65844002510767, 'z_score_var_..."
22,obi_state.DASHUSDT,"[{'z_score_var_9_x': 0.02887528415930756, 'dbi..."
23,obi_state.SUIUSDT,"[{'imbalanceEma': 0.3373680636402701, 'z_score..."
24,obi_state.__wd_cooldown_bybit_orderbook0,[{'instant': 1789042363777874073}]
25,obi_state.ETHUSDT,"[{'regime_cooldown_until': 0, 'z_score9_x': 1...."
26,obi_state.CYBERUSDT,"[{'lq_x': 0.03211738104983445, 'depth_x': 7316..."
27,obi_state.DOTUSDT,"[{'z_score_x_2_x': 0.024918901926988837, 'dask..."
28,obi_state.BTCUSDT,"[{'imbalanceEma': 0.03747719677726424, 'frag_s..."
29,obi_state.STGUSDT,"[{'timestamp': 0, 'z_score9_mu': -0.2630752152..."
30,obi_state.MYXUSDT,"[{'lr_x': 0.11506811969781344, 'imbalanceEma':..."
31,obi_state.BCHUSDT,"[{'z_score_x_2_x': 0.021686869498922155, 'lr_x..."
32,obi_state.TRXUSDT,"[{'symbol': 'TRXUSDT', 'z_score_x_9_x': 0.0040..."
33,obi_state.FILUSDT,"[{'lq_mu': 0.005220889852680102, 'regime_coold..."
34,obi_state.HBARUSDT,"[{'instant': 1789052694812897065, 'z_score2_mu..."
35,obi_state.ARBUSDT,"[{'depth_x': 3190641479.1431556, 'imbalanceEma..."
36,obi_state.OPUSDT,"[{'z_score9_mu': -0.5037828477843946, 'dbid_mu..."
37,obi_state.BNBUSDT,"[{'dbid_x': 2834.511194327468, 'lr_x': 0.31830..."
38,obi_state.MONUSDT,"[{'dask_x': 394522261412.1393, 'imbalanceEma2'..."
39,obi_state.XRPUSDT,"[{'z_score_var_9_mu': -0.9463556632009016, 'z_..."
40,obi_state.__wd_cooldown_bybit_orderbook_x,[{'instant': 1789042363777874073}]
41,obi_state.1000RATSUSDT,"[{'imbalanceEma9': 0.99999999982, 'lr_x': 0.05..."
42,obi_state.XAUUSDT,"[{'z_score2_x': 0.020866986089102313, 'timesta..."
43,obi_state.__wd_cooldown_bybit_orderbook1,[{'instant': 1789042363777874073}]
44,obi_state.PUMPFUNUSDT,"[{'z_score_var_9_mu': -0.8075320671126609, 'z_..."
45,obi_state.LTCUSDT,"[{'frag_fast': 0.0503999064597063, 'z_score9_x..."
46,obi_state.NVDAUSDT,"[{'regime_cooldown_until': 0, 'regime_share': ..."
47,obi_state.JTOUSDT,"[{'regime_cooldown_until': 0, 'lr_mu': -0.1587..."
48,obi_state.APTUSDT,"[{'z_score_var_9_x': 0.0004319147369108872, 'z..."
49,obi_state.XAGUSDT,"[{'bd_x': 422813.1439032562, 'dbid_mu': 278.55..."
50,obi_state.INJUSDT,"[{'symbol': 'INJUSDT', 'lr_x': 0.0567699494431..."
51,obi_state.LINKUSDT,"[{'imbalanceEma9': -0.8019906253215193, 'imbal..."
52,obi_state.ENAUSDT,"[{'dt_fast': 58.148588233849765, 'z_score9_mu'..."
53,obi_state.CLUSDT,"[{'dt_slow': 58.3880703744373, 'z_score_x_9_mu..."
54,obi_state.__wd_cooldown_bybit_orderbook1000,[{'instant': 1789048063778286604}]
55,obi_state.ADAUSDT,"[{'lr_mu': -0.4338860726538833, 'lq_mu': 0.000..."

In [10]:
def values(setting="obi_state",
           code="BTCUSDT"):
    base_url = f"http://r-function-orderbook:8203/api/functions/values/{setting}/{code}"
    response = requests.get(base_url)

    if response.status_code == 200:
        return response.json()
    else:
        print(f"Error: {response.status_code}")
        return None

In [11]:
data=values("obi_state", "BTCUSDT")
df = pd.DataFrame(data["data"])

In [12]:
df

,depth_mu,lr_x,regime_cooldown_until,timestamp,dask_mu,dt_fast,z_score_x_9_mu,imbalanceEma9,depth_x,lq_mu,...,z_score9_x,z_score_var_9_mu,symbol,z_score_var_2_x,lr_mu,bd_mu,frag_slow,instant,frag_fast,bd_x
0,3.862677,0.056596,0,0,0.097377,62.982681,0.470106,0.411532,15.24482,0.002175,...,0.000043,0.470106,BTCUSDT,0.036012,-0.017902,-0.009815,60.47781,1789052704765682911,69.063838,0.205108